config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  resources :posts, only: [:new, :create, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
end

app/models/post_form.rb
class PostForm
  include ActiveModel::Model

  #PostFormクラスのオブジェクトがPostモデルの属性を扱えるようにする
  attr_accessor(
    :text, :image,
    :id, :created_at, :updated_at
  )

  with_options presence: true do
    validates :text
    validates :image
  end

  def update(params, post)
    post.update(params)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update]

  def index
    @posts = Post.all
  end

  def new
    @post_form = PostForm.new
  end

  def create
    @post_form = PostForm.new(post_form_params)
    if @post_form.valid?
      @post_form.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    # @postから情報をハッシュとして取り出し、@post_formとしてインスタンス生成する
    post_attributes = @post.attributes
    @post_form = PostForm.new(post_attributes)
  end

  def update
    # paramsの内容を反映したインスタンスを生成する
    @post_form = PostForm.new(post_form_params)

    # 画像を選択し直していない場合は、既存の画像をセットする
    @post_form.image ||= @post.image.blob

    if @post_form.valid?
      @post_form.update(post_form_params, @post)
      redirect_to root_path
    else
      render :edit
    end
  end

  private
  def post_form_params
    params.require(:post_form).permit(:text, :image)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TagAppRails7</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post_form,  url: url, method: method, id: 'new_post', local: true do |f| %>
<%= render 'shared/error_messages', model: f.object %>
  <div class="message-field">
    <%= f.text_field :text, placeholder: 'type a message' %>
  </div>
  <div class="image-field">
    <div class="click-upload">
      <%= f.file_field :image %>
    </div>
  </div>
  <div class="submit-btn">
    <%= f.submit '送信' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h3>編集ページ</h3>
<%= render partial: 'form', locals: {url: post_path(@post.id), method: :patch} %>

app/views/posts/index.html.erb
<h3>トップページ</h3>
<h3><%= link_to '新規投稿', new_post_path%></h3>
<% @posts.each do |post| %>
  <div class="posted-content">
    <%= image_tag post.image %><br>
    <%= post.text%><br>
    <%= link_to '詳細', post_path(post.id)%>
  </div>
<% end %>

app/views/posts/new.html.erb
<h3>新規投稿ページ</h3>
<%= render partial: 'form', locals: {url: posts_path, method: :post} %>

app/views/posts/show.html.erb
<h3>詳細ページ</h3>
<div class="posted-content">
  <%= image_tag @post.image %>
  <table>
    <tbody>
      <tr>
        <th>名前</th>
        <td><%= @post.text%></td>
      </tr>
    </tbody>
  </table>
  <%= link_to '編集', edit_post_path(@post.id)%>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>